version: '3.8'

services:
  # Nuestro servidor de Node.js
  app-node:
    build: .
    container_name: exitus/mi-app-node
    # No exponemos puertos al en s exterior aquí, solo Nginx lo hará

    # Nuestro servidor Nginx
  servidor-web:
    image: nginx:alpine
    container_name: mi-proxy-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app-node
